#
# DON'T TOUCH THIS
#
# 4
file-version: -1

# Please keep this enabled, it helps me.
bstats: true

# If the periodic save messages should be shown.
show-save: true

#
# This will change the players UUID to the one their character uses.
# Causing plugins to save data per character if coded correctly.
# USE AT YOUR OWN RISK, IT MIGHT BREAK A LOT, NOT SUPPORTED
# MAKE A FULL SERVER BACKUP BEFORE ENABLING THIS
#
use-character-uuid: false

# Location where the player will be tped to show the character menu.
menu-location:
  x: 0.5
  y: 255
  z: 0.5
  world: world
  # Clear nearby armor stands that might have gotten stuck
  clear-stands: true

# Clear chat when character is selected.
clear-chat: false

# Vault integration
# Default Balance: The balance each character will start with. The economy is still handled by your preferred economy plugin.
# Default Group: The default group (PEX, LuckPerms, GroupManger, etc) each character will have.
# Staff Group: The group staff members will get if they go into staff mode.
vault:
  default-balance: 1500
  default-group: default
  staff-group: admin

# Locations shown in the spawn location picker.
# Last location is added automatically.
spawn-locations:
  1:
    icon: COMMAND_BLOCK
    name: "Debug Area"
    x: 3
    y: 5
    z: -9
    yaw: 0
    pitch: 0
    world: world
  2:
    icon: GRASS_BLOCK
    name: "Plains Area"
    x: -290
    y: 4
    z: 0
    yaw: 90
    pitch: 0
    world: world
  3:
    icon: FLINT_AND_STEEL
    name: "Nether Portal"
    x: -24
    y: 5
    z: -5
    yaw: 90
    pitch: 0
    world: world