main: com.foxxite.multicharacter.MultiCharacter
name: MultiCharacter

author: Foxxite
description: Empty plugin
website: https://foxxite.com

version: "1.0.0"
api-version: "1.15"

depend: [ProtocolLib, LibsDisguises]

softdepend: [PlaceholderAPI]

commands:
  multicharacter:
    usage: /<command>

permissions:
  multicharacter.admin:
    default: op
    description: Gives access to admin mode.