main: com.foxxite.multicharacter.MultiCharacter
name: MultiCharacter

author: Foxxite
description: System for multiple characters with their own skins.
website: https://foxxite.com

version: "1.0.5"
api-version: "1.15"

softdepend: [PlaceholderAPI]

commands:
  multicharacter:
    usage: /<command>
    aliases:
      - mc
      - character

permissions:
  multicharacter.switch:
    default: true
    description: Gives access to the logout / switch command.
  multicharacter.save:
    default: op
    description: Gives access to the save command.
  multicharacter.admin:
    default: op
    description: Gives access to admin mode amd save and reload commands.